version: '2'
services:
    nginx:
        container_name: "${NAME}-nginx"
        image: nginx:alpine
        volumes:
            - "./conf/nginx.conf:/etc/nginx/conf.d/default.conf"
            - "./conf/cert:/etc/ssl"
            - "./public:/var/www/html"
        command: /bin/sh -c "nginx -g 'daemon off;'"
        restart: always
        depends_on:
            - php
            - db
        networks:
            sandbox:
                ipv4_address: 172.20.0.2
                aliases:
                    - nginx
    php:
        container_name: "${NAME}-php"
        image: nanoninja/php-fpm:7.2
        restart: always
        volumes:
            - "./conf/:/usr/local/etc/php/conf.d/"
            - "./public:/var/www/html"
        networks:
            sandbox:
                ipv4_address: 172.20.0.3
                aliases:
                    - php
    db:
        container_name: "${NAME}-db"
        image: mysql:5.7.22
        restart: always
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        volumes:
            - "./data/db:/var/lib/mysql"
        networks:
            sandbox:
                ipv4_address: 172.20.0.4
                aliases:
                    - db
networks:
    sandbox:
        driver: bridge
        ipam:
            config:
                - subnet: 172.20.0.0/16
                  gateway: 172.20.0.1
