version: '2'
services:
  nginx:
    container_name: sandbox-nginx
    image: nginx:alpine
    volumes:
      - "./conf/nginx.conf:/etc/nginx/conf.d/default.conf"
      - "./conf/cert:/etc/ssl"
      - "./public:/var/www/html"
    command: /bin/sh -c "nginx -g 'daemon off;'"
    restart: always
    depends_on:
      - php
      - db
    ports:
      - '9999:80'
  php:
    build: images/php
    container_name: sandbox-php
    restart: always
    volumes:
      - "./conf/:/usr/local/etc/php/conf.d/"
      - "./public:/var/www/html"
  db:
    container_name: sandbox-db
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - ".env"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - "./data/db:/var/lib/mysql"
